### ISSUE TITLE
Baichuan-13B-chat转换失败

### ISSUE THREAD

**Issue by lwo2002** [li-plus/chatglm.cpp#117]
平台：Mac M1 pro 内存16G
报错信息：
Traceback (most recent call last):
  File "/Users/lwo2002/chatglm.cpp/chatglm_cpp/convert.py", line 377, in <module>
    main()
  File "/Users/lwo2002/chatglm.cpp/chatglm_cpp/convert.py", line 371, in main
    convert(f, args.model_name_or_path, dtype=args.type)
  File "/Users/lwo2002/chatglm.cpp/chatglm_cpp/convert.py", line 326, in convert
    tokenizer = AutoTokenizer.from_pretrained(model_name_or_path, trust_remote_code=True)
  File "/Users/lwo2002/miniforge3/envs/chatglm/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 685, in from_pretrained
    tokenizer_class = get_class_from_dynamic_module(class_ref, pretrained_model_name_or_path, **kwargs)
  File "/Users/lwo2002/miniforge3/envs/chatglm/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 443, in get_class_from_dynamic_module
    return get_class_in_module(class_name, final_module.replace(".py", ""))
  File "/Users/lwo2002/miniforge3/envs/chatglm/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 164, in get_class_in_module
    module = importlib.import_module(module_path)
  File "/Users/lwo2002/miniforge3/envs/chatglm/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'transformers_modules.Baichuan-13B-Chat'

**Comment by li-plus** [comment]
报错的行号跟最新代码对不上，确认下是否使用了最新的chatglm.cpp代码，如果没有可以pull下

**Comment by onyxin82** [comment]
我也执行convert失败，执行到下面折行代码后卡主，过了一会出现killed，在M1 pro 16G和Ubuntu下都失败，确认已经pull过。
model = auto_model_class.from_pretrained(model_name_or_path, trust_remote_code=True) #388行

**Comment by li-plus** [comment]
@onyxin82 这应该是 oom 了，可以 `dmesg -T` 确认下，13B 的 fp16 模型，转换时至少需要 26GB 的内存了

**Comment by wizardbyron** [comment]
平台: Linux，内存 36G

Traceback (most recent call last):
  File "chatglm_cpp/convert.py", line 445, in <module>
    main()
  File "chatglm_cpp/convert.py", line 439, in main
    convert(f, args.model_name_or_path, dtype=args.type)
  File "chatglm_cpp/convert.py", line 387, in convert
    model = auto_model_class.from_pretrained(model_name_or_path, trust_remote_code=True)
  File "/data/home/directorgu/.local/lib/python3.6/site-packages/transformers/models/auto/auto_factory.py", line 441, in from_pretrained
    pretrained_model_name_or_path, module_file + ".py", class_name, **kwargs
  File "/data/home/directorgu/.local/lib/python3.6/site-packages/transformers/dynamic_module_utils.py", line 384, in get_class_from_dynamic_module
    return get_class_in_module(class_name, final_module.replace(".py", ""))
  File "/data/home/directorgu/.local/lib/python3.6/site-packages/transformers/dynamic_module_utils.py", line 154, in get_class_in_module
    module = importlib.import_module(module_path)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/data/home/directorgu/.cache/huggingface/modules/transformers_modules/baichuan-inc/Baichuan-13B-Chat/e580bc803f3f4f6b42ddccd0730739c057c7b54c/modeling_baichuan.py", line 14, in <module>
    from transformers.generation.utils import GenerationConfig

**Comment by wizardbyron** [comment]
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Traceback (most recent call last):
  File "chatglm_cpp/convert.py", line 377, in <module>
    main()
  File "chatglm_cpp/convert.py", line 371, in main
    convert(f, args.model_name_or_path, dtype=args.type)
  File "chatglm_cpp/convert.py", line 327, in convert
    model = AutoModel.from_pretrained(model_name_or_path, trust_remote_code=True)
  File "/data/home/directorgu/.local/lib/python3.6/site-packages/transformers/models/auto/auto_factory.py", line 448, in from_pretrained
    f"Unrecognized configuration class {config.__class__} for this kind of AutoModel: {cls.__name__}.\n"
ValueError: Unrecognized configuration class <class 'transformers_modules.baichuan-inc.Baichuan-13B-Chat.e580bc803f3f4f6b42ddccd0730739c057c7b54c.configuration_baichuan.BaichuanConfig'> for this kind of AutoModel: AutoModel.
Model type should be one of DPTConfig, DecisionTransformerConfig, GLPNConfig, MaskFormerConfig, PoolFormerConfig, ConvNextConfig, VanConfig, ResNetConfig, YosoConfig, SwinConfig, ViltConfig, ViTMAEConfig, NystromformerConfig, XGLMConfig, ImageGPTConfig, QDQBertConfig, FNetConfig, SegformerConfig, VisionTextDualEncoderConfig, PerceiverConfig, GPTJConfig, LayoutLMv2Config, PLBartConfig, BeitConfig, RemBertConfig, VisualBertConfig, CanineConfig, RoFormerConfig, CLIPConfig, BigBirdPegasusConfig, DeiTConfig, LukeConfig, DetrConfig, GPTNeoConfig, BigBirdConfig, Speech2TextConfig, ViTConfig, Wav2Vec2Config, M2M100Config, ConvBertConfig, LEDConfig, BlenderbotSmallConfig, RetriBertConfig, IBertConfig, MT5Config, T5Config, MobileBertConfig, DistilBertConfig, AlbertConfig, BertGenerationConfig, CamembertConfig, XLMRobertaXLConfig, XLMRobertaConfig, PegasusConfig, MarianConfig, MBartConfig, MegatronBertConfig, MPNetConfig, BartConfig, BlenderbotConfig, ReformerConfig, LongformerConfig, RobertaConfig, DebertaV2Config, DebertaConfig, FlaubertConfig, FSMTConfig, SqueezeBertConfig, HubertConfig, BertConfig, OpenAIGPTConfig, GPT2Config, TransfoXLConfig, XLNetConfig, XLMProphetNetConfig, ProphetNetConfig, XLMConfig, CTRLConfig, ElectraConfig, FunnelConfig, LxmertConfig, DPRConfig, LayoutLMConfig, TapasConfig, SplinterConfig, SEWDConfig, SEWConfig, UniSpeechSatConfig, UniSpeechConfig, WavLMConfig, Data2VecAudioConfig, Data2VecTextConfig.

**Comment by leeswan** [comment]
> 我也执行convert失败，执行到下面折行代码后卡主，过了一会出现killed，在M1 pro 16G和Ubuntu下都失败，确认已经pull过。 model = auto_model_class.from_pretrained(model_name_or_path, trust_remote_code=True) #388行

请问killed这个问题解决了吗？我64G的内存都报这个错误

**Comment by flying-dolphin** [comment]
> > 我也执行convert失败，执行到下面折行代码后卡主，过了一会出现killed，在M1 pro 16G和Ubuntu下都失败，确认已经pull过。 model = auto_model_class.from_pretrained(model_name_or_path, trust_remote_code=True) #388行
> 
> 请问killed这个问题解决了吗？我64G的内存都报这个错误

同问，我70多G free的内存也报这个错，而且是Loading checkpoint shards刚开始0%的时候就killed了

**Comment by taskmgr** [comment]
我用的机器内存96g转换成功，实测转换13b模型到q5_1时占用内存峰值大概能到70g左右，供各位参考

**Comment by summershrimp** [comment]
> 我用的机器内存96g转换成功，实测转换13b模型到q5_1时占用内存峰值大概能到70g左右，供各位参考

能否共享一份转换好的模型文件？ GPU跑的话要多少显存？

**Comment by chenqiny** [comment]
llama.cpp不就可以转吗?
