### ISSUE TITLE
chatglm2 convert.py挂了

### ISSUE THREAD

**Issue by liaoweiguo** [li-plus/chatglm.cpp#13]
│ /home/xxxx/testingllm/chatglm.cpp/convert.py:233 in dump_config                                         │
│                                                                                                  │
│   230 │   │   │   config.multi_query_group_num,                                                  │
│   231 │   │   ]                                                                                  │
│   232 │   │                                                                                      │
│ ❱ 233 │   │   f.write(struct.pack("i" * len(config_values), *config_values))                     │
│   234 │                                                                                          │
│   235 │   @staticmethod                                                                          │
│   236 │   def dump_tokenizer(f, tokenizer):                                                      │

chatglm没问题

**Comment by kavern1128** [comment]
我也遇到同样的问题。

**Comment by liaoweiguo** [comment]
有解决方案吗

**Comment by liaoweiguo** [comment]
glm2比1还是好一点

**Comment by li-plus** [comment]
可以提供下详细报错信息吗，例如调用栈？

**Comment by liaoweiguo** [comment]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /mnt/hda/exgit/chatglm.cpp/convert.py:285 in <module>                                            │
│                                                                                                  │
│   282                                                                                            │
│   283                                                                                            │
│   284 if __name__ == "__main__":                                                                 │
│ ❱ 285 │   main()                                                                                 │
│   286                                                                                            │
│                                                                                                  │
│ /mnt/hda/exgit/chatglm.cpp/convert.py:279 in main                                                │
│                                                                                                  │
│   276 │   │   model = model.merge_and_unload()                                                   │
│   277 │                                                                                          │
│   278 │   if hasattr(model.config, "multi_query_attention"):                                     │
│ ❱ 279 │   │   ChatGLM2Converter.convert(model, tokenizer, ggml_type, args.save_path)             │
│   280 │   else:                                                                                  │
│   281 │   │   ChatGLMConverter.convert(model, tokenizer, ggml_type, args.save_path)              │
│   282                                                                                            │
│                                                                                                  │
│ /mnt/hda/exgit/chatglm.cpp/convert.py:134 in convert                                             │
│                                                                                                  │
│   131 │   │   with open(save_path, "wb") as f:                                                   │
│   132 │   │   │   f.write(b"ggml")  # magic                                                      │
│   133 │   │   │   f.write(struct.pack("ii", cls.MODEL_TYPE.value, 1))  # model type & version    │
│ ❱ 134 │   │   │   cls.dump_config(f, model.config, ggml_type)                                    │
│   135 │   │   │   cls.dump_tokenizer(f, tokenizer)                                               │
│   136 │   │   │   cls.dump_model(f, model, ggml_type)                                            │
│   137                                                                                            │
│                                                                                                  │
│ /mnt/hda/exgit/chatglm.cpp/convert.py:233 in dump_config                                         │
│                                                                                                  │
│   230 │   │   │   config.multi_query_group_num,                                                  │
│   231 │   │   ]                                                                                  │
│   232 │   │                                                                                      │
│ ❱ 233 │   │   f.write(struct.pack("i" * len(config_values), *config_values))                     │
│   234 │                                                                                          │
│   235 │   @staticmethod                                                                          │
│   236 │   def dump_tokenizer(f, tokenizer):                                                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
error: required argument is not an integer

**Comment by liaoweiguo** [comment]
<img width="704" alt="截屏2023-07-03 19 14 19" src="https://github.com/li-plus/chatglm.cpp/assets/22187224/f057e3fa-42c8-4f16-94c9-46fa0c751c95">

**Comment by liaoweiguo** [comment]
上面是ubuntu，Mac上是另一个提示：

python3 convert.py -i THUDM/chatglm2-6b -t q4_0 -o chatglm2-ggml.bin 
Downloading (…)lve/main/config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.14k/1.14k [00:00<00:00, 3.27MB/s]
Downloading (…)iguration_chatglm.py: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.28k/2.28k [00:00<00:00, 6.88MB/s]
A new version of the following files was downloaded from https://huggingface.co/THUDM/chatglm2-6b:
- configuration_chatglm.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.
Traceback (most recent call last):
  File "/Users/weiguoliao/exgit/chatglm.cpp/convert.py", line 285, in <module>
    main()
  File "/Users/weiguoliao/exgit/chatglm.cpp/convert.py", line 270, in main
    tokenizer = AutoTokenizer.from_pretrained(args.model_name_or_path, trust_remote_code=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/transformers/models/auto/tokenization_auto.py", line 719, in from_pretrained
    raise ValueError(
ValueError: Unrecognized configuration class <class 'transformers_modules.THUDM.chatglm2-6b.c57e892806dfe383cd5caf09719628788fe96379.configuration_chatglm.ChatGLMConfig'> to build an AutoTokenizer.
Model type should be one of AlbertConfig, AlignConfig, BartConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, BioGptConfig, BlenderbotConfig, BlenderbotSmallConfig, BlipConfig, Blip2Config, BloomConfig, BridgeTowerConfig, CamembertConfig, CanineConfig, ChineseCLIPConfig, ClapConfig, CLIPConfig, CLIPSegConfig, CodeGenConfig, ConvBertConfig, CpmAntConfig, CTRLConfig, Data2VecTextConfig, DebertaConfig, DebertaV2Config, DistilBertConfig, DPRConfig, ElectraConfig, ErnieConfig, ErnieMConfig, EsmConfig, FlaubertConfig, FNetConfig, FSMTConfig, FunnelConfig, GitConfig, GPT2Config, GPT2Config, GPTBigCodeConfig, GPTNeoConfig, GPTNeoXConfig, GPTNeoXJapaneseConfig, GPTJConfig, GPTSanJapaneseConfig, GroupViTConfig, HubertConfig, IBertConfig, JukeboxConfig, LayoutLMConfig, LayoutLMv2Config, LayoutLMv3Config, LEDConfig, LiltConfig, LlamaConfig, LongformerConfig, LongT5Config, LukeConfig, LxmertConfig, M2M100Config, MarianConfig, MBartConfig, MegaConfig, MegatronBertConfig, MgpstrConfig, MobileBertConfig, MPNetConfig, MT5Config, MvpConfig, NezhaConfig, NllbMoeConfig, NystromformerConfig, OneFormerConfig, OpenAIGPTConfig, OPTConfig, OwlViTConfig, PegasusConfig, PegasusXConfig, PerceiverConfig, Pix2StructConfig, PLBartConfig, ProphetNetConfig, QDQBertConfig, RagConfig, RealmConfig, ReformerConfig, RemBertConfig, RetriBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, RwkvConfig, Speech2TextConfig, Speech2Text2Config, SpeechT5Config, SplinterConfig, SqueezeBertConfig, SwitchTransformersConfig, T5Config, TapasConfig, TransfoXLConfig, ViltConfig, VisualBertConfig, Wav2Vec2Config, Wav2Vec2ConformerConfig, WhisperConfig, XCLIPConfig, XGLMConfig, XLMConfig, XLMProphetNetConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, XmodConfig, YosoConfig.

**Comment by kavern1128** [comment]
> 原因应该是你的 chatglm2-6b 版本比较旧，缺了一些 token_id 的配置，应该在 #21 修复了，可以 pull 下 main 分支试试。

可以了，10700K运行起来很流畅，谢谢大佬^^
