### ISSUE TITLE
keyerror: 'usage' when use openai_api in langchain

### ISSUE THREAD

**Issue by chunzha1** [li-plus/chatglm.cpp#167]
I got error when used langchain to call openai_api:, 
Traceback (most recent call last):
  File "d:\wechatgpt\bingapi\GPT2Bing.py", line 34, in <module>
    result = agent.run("what is the date today? What great events have taken place today in history?")
  File "C:\Users\Xpeng\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\langchain\chains\base.py", line 503, in run
    return self(args[0], callbacks=callbacks, tags=tags, metadata=metadata)[
  File "C:\Users\Xpeng\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\langchain\chains\base.py", line 308, in __call__
    raise e
  File "C:\Users\Xpeng\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\langchain\chains\base.py", line 302, in __call__
    self._call(inputs, run_manager=run_manager)
  File "C:\Users\Xpeng\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\langchain\agents\agent.py", line 1141, in _call
    next_step_output = self._take_next_step(
  File "C:\Users\Xpeng\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\langchain\agents\agent.py", line 928, in _take_next_step
    output = self.agent.plan(
  File "C:\Users\Xpeng\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\langchain\agents\agent.py", line 541, in plan
    full_output = self.llm_chain.predict(callbacks=callbacks, **full_inputs)
  File "C:\Users\Xpeng\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\langchain\chains\llm.py", line 257, in predict
    return self(kwargs, callbacks=callbacks)[self.output_key]
  File "C:\Users\Xpeng\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\langchain\chains\base.py", line 308, in __call__
    raise e
  File "C:\Users\Xpeng\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\langchain\chains\base.py", line 302, in __call__
    self._call(inputs, run_manager=run_manager)
  File "C:\Users\Xpeng\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\langchain\chains\llm.py", line 93, 
in _call
    response = self.generate([inputs], run_manager=run_manager)
  File "C:\Users\Xpeng\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\langchain\chains\llm.py", line 103, in generate
    return self.llm.generate_prompt(
  File "C:\Users\Xpeng\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\langchain\llms\base.py", line 497, 
in generate_prompt
    return self.generate(prompt_strings, stop=stop, callbacks=callbacks, **kwargs)
  File "C:\Users\Xpeng\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\langchain\llms\base.py", line 646, 
in generate
    output = self._generate_helper(
  File "C:\Users\Xpeng\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\langchain\llms\base.py", line 534, 
in _generate_helper
    raise e
  File "C:\Users\Xpeng\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\langchain\llms\base.py", line 521, 
generate_helper
    self._generate(
  File "C:\Users\Xpeng\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\langchain\llms\openai.py", line 900, in _generate
    "token_usage": full_response["usage"],
KeyError: 'usage'
It seems that the API is missing the 'usage' keyword        
usage: {
              "prompt_tokens": 
              "completion_tokens": ,
              "total_tokens": 
            }

**Comment by chunzha1** [comment]
I tried to solve this issue in this pr: https://github.com/li-plus/chatglm.cpp/pull/168
