### ISSUE TITLE
无论在哪个目录运行 web_demo.py 均报错 No module named 'chatglm_cpp'

### ISSUE THREAD

**Issue by mengde8** [li-plus/chatglm.cpp#187]
设备: MacBook Pro; Apple M3; 24 GB; macOS 14.1.1

commit: 95d3b8c1730d646c1916701eaf4ce03fe98baa8c

安装步骤:
```zsh
$ git clone --recursive https://github.com/li-plus/chatglm.cpp.git && cd chatglm.cpp
$ cmake -B build -DGGML_METAL=ON && cmake --build build -j
$ python3 -m venv venv
$ source venv/bin/activate
$ pip install torch tabulate tqdm transformers accelerate sentencepiece
$ python3 chatglm_cpp/convert.py -i ../chatglm3-6b -t f16 -o chatglm3-ggml.bin
```

在M2 MacBook Air上运行完全复现此错误

如下，不论到主目录还是examples目录下均报错`No module named 'chatglm_cpp'`

使用`./build/bin/main -m chatglm3-ggml.bin -p 你好`运行正常

错误展示:
```zsh
(venv) user@macbook examples % pwd
~/work/code/fork/chatglm.cpp/examples

(venv) user@macbook examples % python3 web_demo.py -m ../chatglm3-ggml.bin --temp 0.8 --top_p 0.8
Traceback (most recent call last):
  File "~/work/code/fork/chatglm.cpp/examples/web_demo.py", line 6, in <module>
    import chatglm_cpp
ModuleNotFoundError: No module named 'chatglm_cpp'

(venv) user@macbook examples % cd ..

(venv) user@macbook chatglm.cpp % pwd
~/work/code/fork/chatglm.cpp

(venv) user@macbook chatglm.cpp % python3 examples/web_demo.py -m chatglm3-ggml.bin --temp 0.8 --top_p 0.8
Traceback (most recent call last):
  File "~/work/code/fork/chatglm.cpp/examples/web_demo.py", line 6, in <module>
    import chatglm_cpp
ModuleNotFoundError: No module named 'chatglm_cpp'

(venv) user@macbook chatglm.cpp % ./build/bin/main -m chatglm3-ggml.bin -p 你好
你好👋！我是人工智能助手 ChatGLM3-6B，很高兴见到你，欢迎问我任何问题。
```

pip:
```zsh
(venv) user@macbook chatglm.cpp % pip list
Package            Version
------------------ ---------
accelerate         0.24.1
certifi            2023.7.22
charset-normalizer 3.3.2
filelock           3.13.1
fsspec             2023.10.0
huggingface-hub    0.17.3
idna               3.4
Jinja2             3.1.2
MarkupSafe         2.1.3
mpmath             1.3.0
networkx           3.2.1
numpy              1.26.1
packaging          23.2
pip                21.2.4
psutil             5.9.6
PyYAML             6.0.1
regex              2023.10.3
requests           2.31.0
safetensors        0.4.0
sentencepiece      0.1.99
setuptools         58.0.4
sympy              1.12
tabulate           0.9.0
tokenizers         0.14.1
torch              2.1.0
tqdm               4.66.1
transformers       4.35.0
typing_extensions  4.8.0
urllib3            2.0.7
WARNING: You are using pip version 21.2.4; however, version 23.3.1 is available.
You should consider upgrading via the '~/work/code/fork/chatglm.cpp/venv/bin/python3 -m pip install --upgrade pip' command.
```

**Comment by mengde8** [comment]
克隆后使用`CMAKE_ARGS="-DGGML_METAL=ON" pip install .`解决

**Comment by daxiaolaogui** [comment]
> 克隆后使用`CMAKE_ARGS="-DGGML_METAL=ON" pip install .`解决

克隆是什么意思，可以具体说明一下吗，在哪个目录下执行这个语句？

**Comment by mengde8** [comment]
> > 克隆后使用`CMAKE_ARGS="-DGGML_METAL=ON" pip install .`解决
> 
> 克隆是什么意思，可以具体说明一下吗，在哪个目录下执行这个语句？

克隆指的是git clone 我当时的意思应该是git clone后还要用我发的那个指令安装一遍
