### ISSUE TITLE
小白问题，chatglm3-ggml.bin通过python的pipeline报错

### ISSUE THREAD

**Issue by listenfree** [li-plus/chatglm.cpp#201]
>>> import chatglm_cpp
>>> 
>>> pipeline = chatglm_cpp.Pipeline("../chatglm3-ggml.bin")
>>> pipeline.chat(["你好"])

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.8/site-packages/chatglm_cpp/__init__.py", line 60, in chat
    messages = [_ensure_chat_message(msg) for msg in messages]
  File "/opt/conda/lib/python3.8/site-packages/chatglm_cpp/__init__.py", line 60, in <listcomp>
    messages = [_ensure_chat_message(msg) for msg in messages]
  File "/opt/conda/lib/python3.8/site-packages/chatglm_cpp/__init__.py", line 25, in _ensure_chat_message
    raise TypeError(f"expect message type to be ChatMessage or dict, but got {type(message)}")
TypeError: expect message type to be ChatMessage or dict, but got <class 'str'>

**Comment by li-plus** [comment]
chatglm-cpp 0.3.0 改了 API，已经更新 README，可以这样调用：
```python
>>> import chatglm_cpp
>>> 
>>> pipeline = chatglm_cpp.Pipeline("../chatglm-ggml.bin")
>>> pipeline.chat([chatglm_cpp.ChatMessage(role="user", content="你好")])
ChatMessage(role="assistant", content="你好👋！我是人工智能助手 ChatGLM-6B，很高兴见到你，欢迎问我任何问题。", tool_calls=[])
```

**Comment by listenfree** [comment]
感谢！成功了！
