### ISSUE TITLE
build docker error

### ISSUE THREAD

**Issue by nzlov** [li-plus/chatglm.cpp#207]
```
15.62 Building wheels for collected packages: chatglm-cpp
15.62   Building wheel for chatglm-cpp (pyproject.toml): started
16.21   Building wheel for chatglm-cpp (pyproject.toml): finished with status 'error'
16.22   error: subprocess-exited-with-error
16.22
16.22   × Building wheel for chatglm-cpp (pyproject.toml) did not run successfully.
16.22   │ exit code: 1
16.22   ╰─> [149 lines of output]
16.22       running bdist_wheel
16.22       running build
16.22       running build_py
16.22       creating build
16.22       creating build/lib.linux-x86_64-cpython-38
16.22       creating build/lib.linux-x86_64-cpython-38/chatglm_cpp
16.22       copying chatglm_cpp/convert.py -> build/lib.linux-x86_64-cpython-38/chatglm_cpp
16.22       copying chatglm_cpp/langchain_api.py -> build/lib.linux-x86_64-cpython-38/chatglm_cpp
16.22       copying chatglm_cpp/openai_api.py -> build/lib.linux-x86_64-cpython-38/chatglm_cpp
16.22       copying chatglm_cpp/__init__.py -> build/lib.linux-x86_64-cpython-38/chatglm_cpp
16.22       running egg_info
16.22       writing chatglm_cpp.egg-info/PKG-INFO
16.22       writing dependency_links to chatglm_cpp.egg-info/dependency_links.txt
16.22       writing requirements to chatglm_cpp.egg-info/requires.txt
16.22       writing top-level names to chatglm_cpp.egg-info/top_level.txt
16.22       reading manifest file 'chatglm_cpp.egg-info/SOURCES.txt'
16.22       reading manifest template 'MANIFEST.in'
16.22       adding license file 'LICENSE'
16.22       writing manifest file 'chatglm_cpp.egg-info/SOURCES.txt'
16.22       copying chatglm_cpp/_C.pyi -> build/lib.linux-x86_64-cpython-38/chatglm_cpp
16.22       running build_ext
16.22       -- The CXX compiler identification is GNU 9.4.0
16.22       -- Detecting CXX compiler ABI info
16.22       -- Detecting CXX compiler ABI info - done
16.22       -- Check for working CXX compiler: /usr/bin/c++ - skipped
16.22       -- Detecting CXX compile features
16.22       -- Detecting CXX compile features - done
16.22       CMake Deprecation Warning at third_party/ggml/CMakeLists.txt:1 (cmake_minimum_required):
16.22         Compatibility with CMake < 3.5 will be removed from a future version of
16.22         CMake.
16.22
16.22         Update the VERSION argument <min> value or use a ...<max> suffix to tell
16.22         CMake that the project does not need compatibility with older versions.
16.22
16.22
16.22       -- The C compiler identification is GNU 9.4.0
16.22       -- Detecting C compiler ABI info
16.22       -- Detecting C compiler ABI info - done
16.22       -- Check for working C compiler: /usr/bin/cc - skipped
16.22       -- Detecting C compile features
16.22       -- Detecting C compile features - done
16.22       -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
16.22       -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
16.22       -- Looking for pthread_create in pthreads
16.22       -- Looking for pthread_create in pthreads - not found
16.22       -- Looking for pthread_create in pthread
16.22       -- Looking for pthread_create in pthread - found
16.22       -- Found Threads: TRUE
16.22       -- CMAKE_SYSTEM_PROCESSOR: x86_64
16.22       -- x86 detected
16.22       -- Linux detected
16.22       CMake Deprecation Warning at third_party/sentencepiece/CMakeLists.txt:15 (cmake_minimum_required):
16.22         Compatibility with CMake < 3.5 will be removed from a future version of
16.22         CMake.
16.22
16.22         Update the VERSION argument <min> value or use a ...<max> suffix to tell
16.22         CMake that the project does not need compatibility with older versions.
16.22
16.22
16.22       -- VERSION: 0.2.00
16.22       -- pybind11 v2.11.1
16.22       CMake Warning (dev) at third_party/pybind11/tools/FindPythonLibsNew.cmake:98 (find_package):
16.22         Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
16.22         are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
16.22         the cmake_policy command to set the policy and suppress this warning.
16.22
16.22       Call Stack (most recent call first):
16.22         third_party/pybind11/tools/pybind11Tools.cmake:50 (find_package)
16.22         third_party/pybind11/tools/pybind11Common.cmake:188 (include)
16.22         third_party/pybind11/CMakeLists.txt:210 (include)
16.22       This warning is for project developers.  Use -Wno-dev to suppress it.
16.22
16.22       -- Found PythonInterp: /usr/bin/python3 (found suitable version "3.8.10", minimum required is "3.6")
16.22       -- Found PythonLibs: python3.8
16.22       -- Performing Test HAS_FLTO
16.22       -- Performing Test HAS_FLTO - Success
16.22       -- Configuring done (0.4s)
16.22       CMake Error in CMakeLists.txt:
16.22         Imported target "pybind11::module" includes non-existent path
16.22
16.22           "/usr/include/python3.8"
16.22
16.22         in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
16.22
16.22         * The path was deleted, renamed, or moved to another location.
16.22
16.22         * An install or uninstall procedure did not complete successfully.
16.22
16.22         * The installation package was faulty and references files it does not
16.22         provide.
16.22
16.22
16.22
16.22       -- Generating done (0.0s)
16.22       CMake Generate step failed.  Build files cannot be regenerated correctly.
16.22       Traceback (most recent call last):
16.22         File "/usr/local/lib/python3.8/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
16.22           main()
16.22         File "/usr/local/lib/python3.8/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
16.22           json_out['return_val'] = hook(**hook_input['kwargs'])
16.22         File "/usr/local/lib/python3.8/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
16.22           return _build_backend().build_wheel(wheel_directory, config_settings,
16.22         File "/tmp/pip-build-env-73ckvof0/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 404, in build_wheel
16.22           return self._build_with_temp_dir(
16.22         File "/tmp/pip-build-env-73ckvof0/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 389, in _build_with_temp_dir
16.22           self.run_setup()
16.22         File "/tmp/pip-build-env-73ckvof0/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 311, in run_setup
16.22           exec(code, locals())
16.22         File "<string>", line 127, in <module>
16.22         File "/tmp/pip-build-env-73ckvof0/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 103, in setup
16.22           return distutils.core.setup(**attrs)
16.22         File "/tmp/pip-build-env-73ckvof0/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
16.22           return run_commands(dist)
16.22         File "/tmp/pip-build-env-73ckvof0/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
16.22           dist.run_commands()
16.22         File "/tmp/pip-build-env-73ckvof0/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
16.22           self.run_command(cmd)
16.22         File "/tmp/pip-build-env-73ckvof0/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 963, in run_command
16.22           super().run_command(command)
16.22         File "/tmp/pip-build-env-73ckvof0/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
16.22           cmd_obj.run()
16.22         File "/tmp/pip-build-env-73ckvof0/normal/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 368, in run
16.22           self.run_command("build")
16.22         File "/tmp/pip-build-env-73ckvof0/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
16.22           self.distribution.run_command(command)
16.22         File "/tmp/pip-build-env-73ckvof0/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 963, in run_command
16.22           super().run_command(command)
16.22         File "/tmp/pip-build-env-73ckvof0/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
16.22           cmd_obj.run()
16.22         File "/tmp/pip-build-env-73ckvof0/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 131, in run
16.22           self.run_command(cmd_name)
16.22         File "/tmp/pip-build-env-73ckvof0/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
16.22           self.distribution.run_command(command)
16.22         File "/tmp/pip-build-env-73ckvof0/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 963, in run_command
16.22           super().run_command(command)
16.22         File "/tmp/pip-build-env-73ckvof0/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
16.22           cmd_obj.run()
16.22         File "/tmp/pip-build-env-73ckvof0/overlay/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 88, in run
16.22           _build_ext.run(self)
16.22         File "/tmp/pip-build-env-73ckvof0/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
16.22           self.build_extensions()
16.22         File "/tmp/pip-build-env-73ckvof0/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
16.22           self._build_extensions_serial()
16.22         File "/tmp/pip-build-env-73ckvof0/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
16.22           self.build_extension(ext)
16.22         File "<string>", line 120, in build_extension
16.22         File "/usr/lib/python3.8/subprocess.py", line 516, in run
16.22           raise CalledProcessError(retcode, process.args,
16.22       subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-install-y4sn3uau/chatglm-cpp_5e9b0fcc87b44cbd92e9be7e9de657bd', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-y4sn3uau/chatglm-cpp_5e9b0fcc87b44cbd92e9be7e9de657bd/build/lib.linux-x86_64-cpython-38/chatglm_cpp/', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '-DCMAKE_BUILD_TYPE=Release', '-DCHATGLM_ENABLE_PYBIND=ON', '-DBUILD_SHARED_LIBS=OFF']' returned non-zero exit status 1.
16.22       [end of output]
16.22
16.22   note: This error originates from a subprocess, and is likely not a problem with pip.
16.22   ERROR: Failed building wheel for chatglm-cpp
16.22 Failed to build chatglm-cpp
16.23 ERROR: Could not build wheels for chatglm-cpp, which is required to install pyproject.toml-based projects
------
Dockerfile:54
--------------------
  53 |
  54 | >>> RUN \
  55 | >>>     python3 -m pip install --upgrade -i https://pypi.tuna.tsinghua.edu.cn/simple pip && \
  56 | >>>     python3 -m pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple && \
  57 | >>>     python3 -m pip install --no-cache-dir -f dist 'chatglm-cpp[api]' && \
  58 | >>>     rm -rf dist
  59 |
--------------------
ERROR: failed to solve: process "/bin/sh -c python3 -m pip install --upgrade -i https://pypi.tuna.tsinghua.edu.cn/simple pip &&     python3 -m pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple &&     python3 -m pip install --no-cache-dir -f dist 'chatglm-cpp[api]' &&     rm -rf dist" did not complete successfully: exit code: 1
```

**Comment by waltcow** [comment]
docker 本地构建出错

```
chatglm.cpp git:(main) docker build . --network=host -t chatglm.cpp
[+] Building 1.2s (11/16)                                                         docker:default
 => [internal] load build definition from Dockerfile                                        0.0s
 => => transferring dockerfile: 1.81kB                                                      0.0s
 => [internal] load .dockerignore                                                           0.0s
 => => transferring context: 165B                                                           0.0s
 => [internal] load metadata for docker.io/library/ubuntu:20.04                             0.9s
 => [internal] load build context                                                           0.0s
 => => transferring context: 2.19kB                                                         0.0s
 => [build 1/7] FROM docker.io/library/ubuntu:20.04@sha256:ed4a42283d9943135ed87d4ee34e542  0.0s
 => CACHED [build 2/7] WORKDIR /chatglm.cpp                                                 0.0s
 => CACHED [stage-1 3/7] RUN     sed -e "s/archive.ubuntu.com/mirrors.tuna.tsinghua.edu.cn  0.0s
 => CACHED [build 3/7] RUN     sed -e "s/archive.ubuntu.com/mirrors.tuna.tsinghua.edu.cn/g  0.0s
 => CACHED [build 4/7] RUN     python3 -m pip install --upgrade -i https://pypi.tuna.tsing  0.0s
 => CACHED [build 5/7] ADD . .                                                              0.0s
 => ERROR [build 6/7] RUN     cmake -B build -DGGML_CUBLAS=OFF &&     cmake --build build   0.2s
------
 > [build 6/7] RUN     cmake -B build -DGGML_CUBLAS=OFF &&     cmake --build build -j --config Release:
0.155 -- The CXX compiler identification is GNU 9.4.0
0.164 -- Detecting CXX compiler ABI info
0.200 -- Detecting CXX compiler ABI info - done
0.206 -- Check for working CXX compiler: /usr/bin/c++ - skipped
0.206 -- Detecting CXX compile features
0.207 -- Detecting CXX compile features - done
0.207 CMake Error at CMakeLists.txt:19 (add_subdirectory):
0.207   The source directory
0.207 
0.207     /chatglm.cpp/third_party/ggml
0.207 
0.207   does not contain a CMakeLists.txt file.
0.207 
0.207 
0.207 CMake Error at CMakeLists.txt:24 (add_subdirectory):
0.207   The source directory
0.207 
0.207     /chatglm.cpp/third_party/sentencepiece
0.207 
0.207   does not contain a CMakeLists.txt file.
0.207 
0.207 
0.208 -- Configuring incomplete, errors occurred!
------
Dockerfile:29
--------------------
  28 |     # build cpp binary
  29 | >>> RUN \
  30 | >>>     cmake -B build ${CMAKE_ARGS} && \
  31 | >>>     cmake --build build -j --config Release
  32 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c cmake -B build ${CMAKE_ARGS} &&     cmake --build build -j --config Release" did not complete successfully: exit code: 1
```

**Comment by nzlov** [comment]
clean docker and rebuild
