### ISSUE TITLE
pip安装失败

### ISSUE THREAD

**Issue by futz12** [li-plus/chatglm.cpp#214]
# 系统环境
- Windows 11
- CUDA 11.8 及其对应cudnn
- 显卡 RTX4060
# 报错信息
```
Defaulting to user installation because normal site-packages is not writeable
Processing c:\users\wuyex\documents\chatglm.cpp
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: chatglm-cpp
  Building wheel for chatglm-cpp (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for chatglm-cpp (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [122 lines of output]
      running bdist_wheel
      running build
      running build_py
      copying chatglm_cpp\convert.py -> build\lib.win-amd64-cpython-310\chatglm_cpp
      copying chatglm_cpp\langchain_api.py -> build\lib.win-amd64-cpython-310\chatglm_cpp
      copying chatglm_cpp\openai_api.py -> build\lib.win-amd64-cpython-310\chatglm_cpp
      copying chatglm_cpp\__init__.py -> build\lib.win-amd64-cpython-310\chatglm_cpp
      running egg_info
      writing chatglm_cpp.egg-info\PKG-INFO
      writing dependency_links to chatglm_cpp.egg-info\dependency_links.txt
      writing requirements to chatglm_cpp.egg-info\requires.txt
      writing top-level names to chatglm_cpp.egg-info\top_level.txt
      reading manifest file 'chatglm_cpp.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      writing manifest file 'chatglm_cpp.egg-info\SOURCES.txt'
      copying chatglm_cpp\_C.pyi -> build\lib.win-amd64-cpython-310\chatglm_cpp
      running build_ext
      CMake Deprecation Warning at third_party/ggml/CMakeLists.txt:1 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.

        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.


      -- CMAKE_SYSTEM_PROCESSOR: AMD64
      -- x86 detected
      CMake Deprecation Warning at third_party/sentencepiece/CMakeLists.txt:15 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.

        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.


      -- VERSION: 0.2.00
      -- pybind11 v2.11.1
      CMake Warning (dev) at third_party/pybind11/tools/FindPythonLibsNew.cmake:98 (find_package):
        Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
        are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
        the cmake_policy command to set the policy and suppress this warning.

      Call Stack (most recent call first):
        third_party/pybind11/tools/pybind11Tools.cmake:50 (find_package)
        third_party/pybind11/tools/pybind11Common.cmake:188 (include)
        third_party/pybind11/CMakeLists.txt:210 (include)
      This warning is for project developers.  Use -Wno-dev to suppress it.

      -- Configuring done (0.1s)
      -- Generating done (0.1s)
      -- Build files have been written to: C:/Users/wuyex/Documents/chatglm.cpp/build/temp.win-amd64-cpython-310/Release/chatglm_cpp._C
      适用于 .NET Framework MSBuild 版本 17.8.3+195e7f5a3

        1>Checking Build System
        Building Custom Rule C:/Users/wuyex/Documents/chatglm.cpp/third_party/ggml/src/CMakeLists.txt
        ggml.vcxproj -> C:\Users\wuyex\Documents\chatglm.cpp\build\temp.win-amd64-cpython-310\Release\chatglm_cpp._C\lib\Release\ggml.lib
        Building Custom Rule C:/Users/wuyex/Documents/chatglm.cpp/third_party/sentencepiece/src/CMakeLists.txt
        sentencepiece-static.vcxproj -> C:\Users\wuyex\Documents\chatglm.cpp\build\temp.win-amd64-cpython-310\Release\chatglm_cpp._C\lib\Release\sentencepiece.lib
        Building Custom Rule C:/Users/wuyex/Documents/chatglm.cpp/CMakeLists.txt
        chatglm.vcxproj -> C:\Users\wuyex\Documents\chatglm.cpp\build\temp.win-amd64-cpython-310\Release\chatglm_cpp._C\lib\Release\chatglm.lib
        Building Custom Rule C:/Users/wuyex/Documents/chatglm.cpp/CMakeLists.txt
          正在创建库 C:/Users/wuyex/Documents/chatglm.cpp/build/temp.win-amd64-cpython-310/Release/chatglm_cpp._C/lib/Release/_C.lib 和对象 C:/Users/wuyex/Documents/chatglm.cpp/build/temp.win-amd64-cpython-310/Release/chatglm_cpp._C/lib/Release/_C.exp
      chatglm.lib(chatglm.obj) : error LNK2019: 无法解析的外部符号 ggml_cuda_transform_tensor，函数 "public: struct ggml_tensor * __cdecl chatglm::GLMContextMasker::operator()(struct chatglm::ModelContext *,struct ggml_tensor *,int)const " (??RGLMContextMasker@chatglm@@QEBAPEAUggml_tensor@@PEAUModelContext@1@PEAU2@H@Z) 中引用了该符号 [C:\Users\wuyex\Documents\chatglm.cpp\build\temp.win-amd64-cpython-310\Release\chatglm_cpp._C\_C.vcxproj]
      chatglm.lib(chatglm.obj) : error LNK2019: 无法解析的外部符号 ggml_cuda_free_data，函数 "protected: virtual __cdecl chatglm::BasicModelForCausalLM<class chatglm::BasicModel<class chatglm::BasicBlock<class chatglm::RMSNorm,class chatglm::BasicAttention<1,1,0,struct chatglm::BasicRoper<2,1>,0,struct chatglm::CausalContextMasker>,class chatglm::BasicGLU<1,0> >,class chatglm::RMSNorm,struct chatglm::BasicPositionIdsGenerator> >::~BasicModelForCausalLM<class chatglm::BasicModel<class chatglm::BasicBlock<class chatglm::RMSNorm,class chatglm::BasicAttention<1,1,0,struct chatglm::BasicRoper<2,1>,0,struct chatglm::CausalContextMasker>,class chatglm::BasicGLU<1,0> >,class chatglm::RMSNorm,struct chatglm::BasicPositionIdsGenerator> >(void)" (??1?$BasicModelForCausalLM@V?$BasicModel@V?$BasicBlock@VRMSNorm@chatglm@@V?$BasicAttention@$00$00$0A@U?$BasicRoper@$01$00@chatglm@@$0A@UCausalContextMasker@2@@2@V?$BasicGLU@$00$0A@@2@@chatglm@@VRMSNorm@2@UBasicPositionIdsGenerator@2@@chatglm@@@chatglm@@MEAA@XZ) 中引用了该符号 [C:\Users\wuyex\Documents\chatglm.cpp\build\temp.win-amd64-cpython-310\Release\chatglm_cpp._C\_C.vcxproj]
      chatglm.lib(chatglm.obj) : error LNK2019: 无法解析的外部符号 ggml_cuda_assign_buffers，函数 "public: struct ggml_tensor * __cdecl chatglm::BasicRoper<2,1>::operator()(struct chatglm::ModelContext *,struct ggml_tensor *,struct ggml_tensor *,int)const " (??R?$BasicRoper@$01$00@chatglm@@QEBAPEAUggml_tensor@@PEAUModelContext@1@PEAU2@1H@Z) 中引用了该符号 [C:\Users\wuyex\Documents\chatglm.cpp\build\temp.win-amd64-cpython-310\Release\chatglm_cpp._C\_C.vcxproj]
      chatglm.lib(chatglm.obj) : error LNK2019: 无法解析的外部符号 ggml_cuda_set_scratch_size，函数 "public: __cdecl chatglm::BaseModelForCausalLM::BaseModelForCausalLM(class chatglm::ModelConfig,unsigned __int64,unsigned __int64,unsigned __int64)" (??0BaseModelForCausalLM@chatglm@@QEAA@VModelConfig@1@_K11@Z) 中引用了该符号 [C:\Users\wuyex\Documents\chatglm.cpp\build\temp.win-amd64-cpython-310\Release\chatglm_cpp._C\_C.vcxproj]
      C:\Users\wuyex\Documents\chatglm.cpp\build\lib.win-amd64-cpython-310\chatglm_cpp\_C.cp310-win_amd64.pyd : fatal error LNK1120: 4 个无法解析的外部命令 [C:\Users\wuyex\Documents\chatglm.cpp\build\temp.win-amd64-cpython-310\Release\chatglm_cpp._C\_C.vcxproj]
      Traceback (most recent call last):
        File "C:\Program Files\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Program Files\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Program Files\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "C:\Users\wuyex\AppData\Local\Temp\pip-build-env-elwra65d\overlay\Lib\site-packages\setuptools\build_meta.py", line 404, in build_wheel
          return self._build_with_temp_dir(
        File "C:\Users\wuyex\AppData\Local\Temp\pip-build-env-elwra65d\overlay\Lib\site-packages\setuptools\build_meta.py", line 389, in _build_with_temp_dir
          self.run_setup()
        File "C:\Users\wuyex\AppData\Local\Temp\pip-build-env-elwra65d\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 127, in <module>
        File "C:\Users\wuyex\AppData\Local\Temp\pip-build-env-elwra65d\overlay\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\wuyex\AppData\Local\Temp\pip-build-env-elwra65d\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\Users\wuyex\AppData\Local\Temp\pip-build-env-elwra65d\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\wuyex\AppData\Local\Temp\pip-build-env-elwra65d\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\wuyex\AppData\Local\Temp\pip-build-env-elwra65d\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\wuyex\AppData\Local\Temp\pip-build-env-elwra65d\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\wuyex\AppData\Local\Temp\pip-build-env-elwra65d\normal\Lib\site-packages\wheel\bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "C:\Users\wuyex\AppData\Local\Temp\pip-build-env-elwra65d\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\wuyex\AppData\Local\Temp\pip-build-env-elwra65d\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\wuyex\AppData\Local\Temp\pip-build-env-elwra65d\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\wuyex\AppData\Local\Temp\pip-build-env-elwra65d\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "C:\Users\wuyex\AppData\Local\Temp\pip-build-env-elwra65d\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\wuyex\AppData\Local\Temp\pip-build-env-elwra65d\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\wuyex\AppData\Local\Temp\pip-build-env-elwra65d\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\wuyex\AppData\Local\Temp\pip-build-env-elwra65d\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 88, in run
          _build_ext.run(self)
        File "C:\Users\wuyex\AppData\Local\Temp\pip-build-env-elwra65d\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
          self.build_extensions()
        File "C:\Users\wuyex\AppData\Local\Temp\pip-build-env-elwra65d\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "C:\Users\wuyex\AppData\Local\Temp\pip-build-env-elwra65d\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "<string>", line 121, in build_extension
        File "C:\Program Files\Python310\lib\subprocess.py", line 526, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '-j']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for chatglm-cpp
Failed to build chatglm-cpp
ERROR: Could not build wheels for chatglm-cpp, which is required to install pyproject.toml-based projects

[notice] A new release of pip is available: 23.0.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip
```

**Comment by ppbit-lp** [comment]
Can U tell me how to fix it?
