### ISSUE TITLE
我想启动web端提醒这个报错，你们遇到过吗，麻烦给指点一下

### ISSUE THREAD

**Issue by dongyongwei** [li-plus/chatglm.cpp#259]
(base) root@ai:~/chatglm.cpp/examples# python3 web_demo.py -m ../chatglm-ggml.bin
Traceback (most recent call last):
  File "/root/chatglm.cpp/examples/web_demo.py", line 24, in <module>
    pipeline = chatglm_cpp.Pipeline(args.model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/site-packages/chatglm_cpp/__init__.py", line 33, in __init__
    super().__init__(str(model_path))
RuntimeError: /tmp/pip-install-g7k57662/chatglm-cpp_f0d0b14b283d4034978c4aac7fe3f802/chatglm.cpp:323 check failed (data != MAP_FAILED) Invalid argument

**Comment by xpcloud** [comment]
我是启动api也是同样的错误：File "/usr/local/anaconda3/envs/chat/lib/python3.10/site-packages/chatglm_cpp/__init__.py", line 33, in __init__
    super().__init__(str(model_path))
RuntimeError: /tmp/pip-install-8umdz0sz/chatglm-cpp_132bd28a1c4646da894500322fb5060b/chatglm.cpp:323 check failed (data != MAP_FAILED) Invalid argument

**Comment by jjbb** [comment]
我也遇到了同样的问题，然后看了眼chatglm-ggml.bin文件的大小，只有0。于是重新执行了下生成chatglm-ggml.bin的命令，再启动就成功了

**Comment by wac81** [comment]
> 我也遇到了同样的问题，然后看了眼chatglm-ggml.bin文件的大小，只有0。于是重新执行了下生成chatglm-ggml.bin的命令，再启动就成功了
我也大意了
