### ISSUE TITLE
Can't use web_demo in glm4

### ISSUE THREAD

**Issue by jtc1246** [li-plus/chatglm.cpp#308]
Traceback (most recent call last):
  File "/Users/jtc/Downloads/chatglm/glm4/chatglm.cpp/examples/./web_demo.py", line 24, in <module>
    pipeline = chatglm_cpp.Pipeline(args.model)
  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/chatglm_cpp/__init__.py", line 33, in __init__
    super().__init__(str(model_path))
RuntimeError: /Users/jtc/Downloads/chatglm/chatglm.cpp/chatglm.cpp:1570 invalid model type 4

通过cd ./chatglm.cpp/examples && py ./web_demo.py -m ../../chatglm-ggml.bin启动

目前命令行可以正常使用

**Comment by jtc1246** [comment]
Need to reinstall chatglm-cpp in pip, use pip install -U chatglm-cpp.
