### ISSUE TITLE
Python Binding install error at windows 

### ISSUE THREAD

**Issue by dlutsniper** [li-plus/chatglm.cpp#87]
Python Binding 安装报错

cmake版本信息
cmake version 3.27.1
CMake suite maintained and supported by Kitware (kitware.com/cmake).

c++版本信息
c++.exe (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

gcc版本信息
gcc.exe (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

make 版本信息
$ make --version
GNU Make 4.2.1
Built for x86_64-w64-mingw32
Copyright (C) 1988-2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

ncvv版本信息
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Jul_11_03:10:21_Pacific_Daylight_Time_2023
Cuda compilation tools, release 12.2, V12.2.128
Build cuda_12.2.r12.2/compiler.33053471_0

python版本信息
$ python -V
Python 3.10.11

硬件信息
AMD Ryzen 7 5800H with Radeon Graphics            3.20 GHz
16.0 GB (15.3 GB 可用)
NVIDIA T600 GPU

命令
 CMAKE_ARGS="-DGGML_CUBLAS=ON" pip install -U chatglm-cpp

日志
`
$ CMAKE_ARGS="-DGGML_CUBLAS=ON" pip install -U chatglm-cpp
Collecting chatglm-cpp
  Using cached chatglm-cpp-0.2.3.tar.gz (2.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: chatglm-cpp
  Building wheel for chatglm-cpp (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for chatglm-cpp (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [88 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-310
      creating build\lib.win-amd64-cpython-310\chatglm_cpp
      copying chatglm_cpp\langchain_api.py -> build\lib.win-amd64-cpython-310\chatglm_cpp
      copying chatglm_cpp\openai_api.py -> build\lib.win-amd64-cpython-310\chatglm_cpp
      copying chatglm_cpp\__init__.py -> build\lib.win-amd64-cpython-310\chatglm_cpp
      running egg_info
      writing chatglm_cpp.egg-info\PKG-INFO
      writing dependency_links to chatglm_cpp.egg-info\dependency_links.txt
      writing requirements to chatglm_cpp.egg-info\requires.txt
      writing top-level names to chatglm_cpp.egg-info\top_level.txt
      reading manifest file 'chatglm_cpp.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      writing manifest file 'chatglm_cpp.egg-info\SOURCES.txt'
      running build_ext
      -- Building for: NMake Makefiles
      CMake Error at CMakeLists.txt:2 (project):
        Generator

          NMake Makefiles

        does not support platform specification, but platform

          x64

        was specified.

      CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "C:\Users\lzkj\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\lzkj\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\lzkj\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "C:\Users\lzkj\AppData\Local\Temp\pip-build-env-sym66yxt\overlay\Lib\site-packages\setuptools\build_meta.py", line 416, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "C:\Users\lzkj\AppData\Local\Temp\pip-build-env-sym66yxt\overlay\Lib\site-packages\setuptools\build_meta.py", line 401, in _build_with_temp_dir
          self.run_setup()
        File "C:\Users\lzkj\AppData\Local\Temp\pip-build-env-sym66yxt\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 126, in <module>
        File "C:\Users\lzkj\AppData\Local\Temp\pip-build-env-sym66yxt\overlay\Lib\site-packages\setuptools\__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\lzkj\AppData\Local\Temp\pip-build-env-sym66yxt\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\Users\lzkj\AppData\Local\Temp\pip-build-env-sym66yxt\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\lzkj\AppData\Local\Temp\pip-build-env-sym66yxt\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\lzkj\AppData\Local\Temp\pip-build-env-sym66yxt\overlay\Lib\site-packages\setuptools\dist.py", line 1234, in run_command
          super().run_command(command)
        File "C:\Users\lzkj\AppData\Local\Temp\pip-build-env-sym66yxt\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\lzkj\AppData\Local\Temp\pip-build-env-sym66yxt\normal\Lib\site-packages\wheel\bdist_wheel.py", line 349, in run
          self.run_command("build")
        File "C:\Users\lzkj\AppData\Local\Temp\pip-build-env-sym66yxt\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\lzkj\AppData\Local\Temp\pip-build-env-sym66yxt\overlay\Lib\site-packages\setuptools\dist.py", line 1234, in run_command
          super().run_command(command)
        File "C:\Users\lzkj\AppData\Local\Temp\pip-build-env-sym66yxt\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\lzkj\AppData\Local\Temp\pip-build-env-sym66yxt\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "C:\Users\lzkj\AppData\Local\Temp\pip-build-env-sym66yxt\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\lzkj\AppData\Local\Temp\pip-build-env-sym66yxt\overlay\Lib\site-packages\setuptools\dist.py", line 1234, in run_command
          super().run_command(command)
        File "C:\Users\lzkj\AppData\Local\Temp\pip-build-env-sym66yxt\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\lzkj\AppData\Local\Temp\pip-build-env-sym66yxt\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 84, in run
          _build_ext.run(self)
        File "C:\Users\lzkj\AppData\Local\Temp\pip-build-env-sym66yxt\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
          self.build_extensions()
        File "C:\Users\lzkj\AppData\Local\Temp\pip-build-env-sym66yxt\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "C:\Users\lzkj\AppData\Local\Temp\pip-build-env-sym66yxt\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "<string>", line 119, in build_extension
        File "C:\Users\lzkj\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 526, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\lzkj\\AppData\\Local\\Temp\\pip-install-ar25k9ef\\chatglm-cpp_66e01c45f29e4047a8b2daf5389b40d0', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\lzkj\\AppData\\Local\\Temp\\pip-install-ar25k9ef\\chatglm-cpp_66e01c45f29e4047a8b2daf5389b40d0\\build\\lib.win-amd64-cpython-310\\chatglm_cpp\\', '-DPYTHON_EXECUTABLE=C:\\Users\\lzkj\\AppData\\Local\\Programs\\Python\\Python310\\python.exe', '-DCMAKE_BUILD_TYPE=Release', '-DCHATGLM_ENABLE_PYBIND=ON', '-DGGML_CUBLAS=ON', '-A', 'x64', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\lzkj\\AppData\\Local\\Temp\\pip-install-ar25k9ef\\chatglm-cpp_66e01c45f29e4047a8b2daf5389b40d0\\build\\lib.win-amd64-cpython-310\\chatglm_cpp']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for chatglm-cpp
Failed to build chatglm-cpp
ERROR: Could not build wheels for chatglm-cpp, which is required to install pyproject.toml-based projects
`

**Comment by cczhong11** [comment]
可以尝试安装编译后的wheel，下载在这里 https://github.com/cczhong11/chatglm.cpp/actions/runs/5904410708 的artifacts

**Comment by dlutsniper** [comment]
> 可以尝试安装编译后的wheel，下载在这里 https://github.com/cczhong11/chatglm.cpp/actions/runs/5904410708 的artifacts

谢谢，我通过wsl在linux环境跑通了/(ㄒoㄒ)/~~，这个wheel我收下了 感谢✌
![Suggestion](https://github.com/li-plus/chatglm.cpp/assets/30826840/fd5d5c0d-5581-4933-aa12-0f05355c7568)
️

**Comment by dlutsniper** [comment]
通过wsl在linux环境跑通了
